
export interface LoginProperties {
name?:String; 
displayName?:String;
logo?:String;
logoAlternateText?:String;
id?:Number;
description?:Text;
template?:Text;
width?:Number;
height?:Number;
positionX?:String;
positionY?:String;
padding?:any;
language?:any;
labelPosition?:any;
errorMessagePosition ?:any;
helpTextPosition ?:any;
className?:any;
style?:any;
url?:any;
dataset?:any;
method ?:any;
hasCaptcha ?:any;
hasRememberMe ?:any;
hasForgotPassword ?:any;
hasOauth ?:any;
oauthList ?:any;
liveValidation ?:any;
validationOnSubmit ?:any;
validationMessagePosition ?:any;
validationTextSize?:any;
validationTextColor?:any;
validationHilightColor?:any;
html?:any;
jsCode?:any;
call ?:any;
callServer?:any;
target?:any; 
}
